# Generated by Django 6.0.6 on 2026-06-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png", upload_to="avatars/"
            ),
        ),
    ]
