# Generated by Django 6.0.6 on 2026-06-23 12:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default="", verbose_name="Description"
            ),
        ),
    ]
