# Generated by Django 6.0.6 on 2026-06-17 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="item_image",
        ),
    ]
