# Generated by Django 6.0.6 on 2026-06-17 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_remove_items_item_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Items",
            new_name="Item",
        ),
    ]
