# Generated by Django 6.0.6 on 2026-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_rename_items_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="static/food/images/000_menu_placeholder.png", max_length=500
            ),
        ),
    ]
