# Generated by Django 6.0.6 on 2026-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://storage.googleapis.com/ds-builder-bucket/000_menu_placeholder.png",
                max_length=500,
            ),
        ),
    ]
