# Generated by Django 6.0.6 on 2026-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0006_item_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("Vegetarian", "Vegetarian"),
                    ("Non-Vegetarian", "Non-Vegetarian"),
                    ("Mixed", "Mixed"),
                ],
                default="Mixed",
                max_length=20,
            ),
        ),
    ]
