# Generated by Django 6.0.6 on 2026-06-22 16:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0007_item_meal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
    ]
