# Generated by Django 6.0.6 on 2026-06-29 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0009_alter_item_item_name_alter_item_item_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["author", "item_name", "item_price"],
                name="food_item_author__d807f3_idx",
            ),
        ),
    ]
